### PR TITLE
Added CommandAction (Runs a command, and performs super)

### LINKED ISSUE #7: CommandAction
Something to run commands with options for running as server or as player.

### PR DESCRIPTION
**Pull request by Redrield**
Also added @see to javadocs for Action.

Fixes #7

### CODE REVIEW

**Comment by codeHusky** [comment]
I feel like always running super is a bad idea.

**Comment by Redrield** [comment]
Not running super is even worse. Because then inheritance is pointless, you've given it an action type to fufill and it never does it. For people who want to close the GUI after running some other command, what are they expected to do? If they don't want to do anything, they make the type NORMAL. trying to solve for stupidity by limiting the functionality of the API is a bad idea

**Comment by codeHusky** [comment]
No, I just don't want it to be mandatory. Users shouldn't have to do something after a runnable / command but that forces them to.

**Comment by Redrield** [comment]
Then having the runnable/command actions inherit from Action is inherently flawed. Like I said if they don't want to do anything, they can set the action type to NORMAL or NONE. But the API design is broken for people who _want_ to do something, like BACK or CLOSE on a command/runnable Action and they can't.

**Comment by codeHusky** [comment]
It's not flawed, it just makes sense. Having to specify action type when you set it would be irritating.

**Comment by Redrield** [comment]
You have to specify ActionType no matter what to fufill the super constructor. At this point NOT calling super in runAction is flawed.

**Comment by codeHusky** [comment]
tmw you forgot

**Comment by Redrield** [comment]
what?

**Comment by Redrield** [comment]
@codeHusky Gonna merge?

**Pull request merged**
